Repository uccser/cs-unplugged, pull requests merged in 2018-09, with the labels that each got.

#1040 Remove 'odd-parroty-parity' image as word play doesn't work across languages
  csunplugged/topics/content/en/error-detection-and-correction/unit-plan/unit-plan.md
  csunplugged/topics/content/xx_LR/error-detection-and-correction/unit-plan/unit-plan.md
Labels: content: topics/unit plans/lessons

#1041 Remove unused 'crowdin' package (fixes #987)
  docs/source/author/translations.rst
  docs/source/developer/translation_infrastructure.rst
  infrastructure/crowdin/crowdin_bot_python_package/crowdin_bot/__init__.py
  infrastructure/crowdin/crowdin_bot_python_package/crowdin_bot/api.py
  infrastructure/crowdin/crowdin_bot_python_package/crowdin_bot/download_xliff.py
  infrastructure/crowdin/crowdin_bot_python_package/crowdin_bot/get_complete_translations.py
  infrastructure/crowdin/crowdin_bot_python_package/crowdin_bot/get_crowdin_files.py
  infrastructure/crowdin/crowdin_bot_python_package/crowdin_bot/get_crowdin_languages.py
  infrastructure/crowdin/crowdin_bot_python_package/crowdin_bot/get_language_map.py
  infrastructure/crowdin/crowdin_bot_python_package/crowdin_bot/modify_pseudo_translations.py
  infrastructure/crowdin/crowdin_bot_python_package/setup.py
  infrastructure/crowdin/crowdin_bot_scripts/crowdin-bot-config.sh
  infrastructure/crowdin/crowdin_bot_scripts/crowdin-bot-list-unused.sh
  infrastructure/crowdin/crowdin_bot_scripts/crowdin-bot-pull-incontext.sh
  infrastructure/crowdin/crowdin_bot_scripts/crowdin-bot-pull-translations.sh
  infrastructure/crowdin/crowdin_bot_scripts/crowdin-bot-push-source.sh
  infrastructure/crowdin/crowdin_bot_scripts/crowdin-bot-update-messages.sh
  infrastructure/crowdin/crowdin_bot_scripts/crowdin-bot-utils.sh
  infrastructure/crowdin/crowdin_bot_secrets/crowdin_api_key.enc
  infrastructure/crowdin/crowdin_bot_secrets/gce_key.enc
  infrastructure/crowdin/crowdin_bot_secrets/uccser_bot_token.enc
  infrastructure/crowdin/deploy.sh
  infrastructure/crowdin/encrypt-secrets.sh
  infrastructure/crowdin/setup-instance.sh
Labels: infrastructure

#1047 Add not available badge if prerequisite lesson has no translation available.
  csunplugged/templates/topics/curriculum-integration.html
Labels: bug

#1048 Provide clearer translation strings for pages unavailable in a specific language
  csunplugged/classic/models.py
  csunplugged/general/models.py
  csunplugged/resources/models.py
  csunplugged/templates/404.html
  csunplugged/templates/search/search.html
  csunplugged/templates/topics/curriculum-integration.html
  csunplugged/templates/topics/lesson.html
  csunplugged/templates/topics/not-available-warning.html
  csunplugged/templates/topics/programming-challenge-language-solution.html
  csunplugged/templates/topics/programming-challenge.html
  csunplugged/templates/topics/topic.html
  csunplugged/templates/topics/unit-plan-description.html
  csunplugged/templates/topics/unit-plan.html
  csunplugged/tests/classic/models/test_classic_page.py
  csunplugged/tests/general/models/test_general_page.py
  csunplugged/tests/resources/models/test_resource.py
  csunplugged/tests/topics/models/test_curriculum_area.py
  csunplugged/tests/topics/models/test_curriculum_integration.py
  csunplugged/tests/topics/models/test_lesson.py
  csunplugged/tests/topics/models/test_programming_challenge.py
  csunplugged/tests/topics/models/test_topic.py
  csunplugged/tests/topics/models/test_unit_plan.py
  csunplugged/topics/models.py
Labels: frontend, internationalization

#1050 Add warning to resource page if not translated.
  csunplugged/templates/resources/resource.html
  csunplugged/templates/topics/not-available-warning.html
Labels: bug, frontend, internationalization

#1055 Add 'update_lite' command for faster local development
  csu
  csunplugged/general/management/commands/updatedata.py
  csunplugged/tests/general/management/test_updatedata_command.py
  csunplugged/tests/utils/assets/lite-loader/text.md
  csunplugged/tests/utils/test_BaseLoader.py
  csunplugged/topics/management/commands/_LessonsLoader.py
  csunplugged/topics/management/commands/_TopicLoader.py
  csunplugged/topics/management/commands/_UnitPlanLoader.py
  csunplugged/topics/management/commands/loadtopics.py
  csunplugged/utils/BaseLoader.py
Labels: backend

#1069 Source string corrections.
  csunplugged/topics/content/en/binary-numbers/unit-plan/lessons/how-binary-digits-work.md
  csunplugged/topics/content/en/kidbots/curriculum-integrations/storytelling.md
  csunplugged/topics/content/en/kidbots/kidbots.md
  csunplugged/topics/content/en/kidbots/unit-plan/lessons/fitness-unplugged-ct-links.md
  csunplugged/topics/content/en/kidbots/unit-plan/lessons/fitness-unplugged.md
  csunplugged/topics/content/en/kidbots/unit-plan/lessons/rescue-mission-ct-links.md
  csunplugged/topics/content/en/kidbots/unit-plan/lessons/sending-a-rocket-to-mars-ct-links.md
  csunplugged/topics/content/en/kidbots/unit-plan/unit-plan.md
Labels: bug, content: topics/unit plans/lessons
