Repository uccser/cs-unplugged, pull requests merged in 2020-09, with the labels that each got.

#1425 Use Google Tag Manager
  csunplugged/templates/core.html
Labels: backend

#1439 Put programming reminders in a Markdown file
  csunplugged/static/scss/pygments-colorful.scss
  csunplugged/static/scss/pygments-vs.scss
  csunplugged/static/scss/website.scss
  csunplugged/templates/plugging_it_in/programming-challenge.html
  csunplugged/topics/content/en/binary-numbers/programming-challenges/binary-cards-representing-any-number/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/binary-cards-representing-number/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/binary-notes-representing-any-number/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/binary-notes-representing-number/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/binary-numbers-no-calculations/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/binary-numbers-using-variable-operator-repeat/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/binary-numbers-using-variable/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/binary-numbers-using-variables-as-operator/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/cards-given-number-one-line/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/cards-given-number/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/count-5-bw-no-loop/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/count-5-bw-one-input-no-loop/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/count-5-bw-one-input-using-loop/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/count-5-bw-using-loop/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/count-bw-one-input-using-loop/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/decimal-to-binary-alternative/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/decimal-to-binary/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/dots-largest-to-1/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/dots-right-left/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/left-right-given-largest/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/number-bits-representing-number/python-expected.md
  csunplugged/topics/content/en/binary-numbers/programming-challenges/number-cards-display/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/add-in-parts-1-digit-number/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/add-in-parts-2-digit-number/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/calculate-exponents/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/calculate-inside-angles-of-regular-polygons/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/check-if-divisor-series/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/check-if-divisor/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/check-prime/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/find-factors/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/find-prime-factors/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/flip-coins/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/generate-primes/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/go-up-1-10-100-numbers/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/go-up-10-numbers/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/modulo-add-hours-12-hour-clock-without-mod/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/modulo-add-hours-12-hour-clock/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/modulo-add-hours-24-hour-clock/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/modulo-add-months/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/modulo-add-video-timings/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/modulo-check-divisor/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/modulo-check-leap-year/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/modulo-display-midi-note/python-expected.md
  csunplugged/topics/content/en/kidbots/programming-challenges/modulo-even-odd-numbers/python-expected.md
  csunplugged/topics/content/en/programming-reminders-python.md
  csunplugged/topics/management/commands/_ProgrammingChallengesStructureLoader.py
  csunplugged/topics/migrations/0097_programmingchallengeimplementation_programming_reminders.py
  csunplugged/topics/migrations/0098_auto_20200911_0307.py
  csunplugged/topics/migrations/0099_auto_20200914_0319.py
  csunplugged/topics/models.py
  csunplugged/topics/translation.py
Labels: bug, content:plugging-it-in, internationalization

#1444 Match footer colour to header colour
  csunplugged/static/scss/at-home-footer.scss
  csunplugged/static/scss/bootstrap-overrides.scss
  csunplugged/static/scss/core-variables.scss
  csunplugged/static/scss/plugging-it-in-footer.scss
  csunplugged/static/scss/website.scss
  csunplugged/templates/base-at-home.html
  csunplugged/templates/base-plugging-it-in.html
Labels: frontend

#1445 Plugging it in navigation touch ups based on user feedback
  csunplugged/static/img/plugging-it-in/icons8-external-link.svg
  csunplugged/static/img/plugging-it-in/icons8-menu-24.png
  csunplugged/static/js/editor-options-menu.js
  csunplugged/static/scss/programming-editor.scss
  csunplugged/templates/plugging_it_in/programming-challenge.html
  csunplugged/topics/content/en/programming-reminders-python.md
Labels: frontend

#1448 Add walk-through for plugging it in
  LICENCE-THIRD-PARTY
  csunplugged/package.json
  csunplugged/static/css/third-party/introjs-modern.css
  csunplugged/static/css/third-party/introjs.css
  csunplugged/static/js/plugging-it-in-walkthrough.js
  csunplugged/static/scss/programming-editor.scss
  csunplugged/templates/plugging_it_in/programming-challenge.html
  csunplugged/templates/plugging_it_in/results-table.html
  third-party-licences/introjs.txt
Labels: content:plugging-it-in

#1449 Improve consistency of blues in the PII colour scheme
  csunplugged/static/scss/plugging-it-in-base.scss
  csunplugged/static/scss/plugging-it-in-footer.scss
  csunplugged/static/scss/programming-editor.scss
  csunplugged/templates/base-plugging-it-in.html
  csunplugged/templates/plugging_it_in/about.html
  csunplugged/templates/plugging_it_in/index.html
Labels: frontend
