Repository uccser/cs-unplugged, pull requests merged in 2020-08, with the labels that each got.

#1397 Host videos on Vimeo instead of YouTube
  csunplugged/at_home/content/en/binary-challenge/more-information.md
  csunplugged/static/js/website.js
  csunplugged/templates/core.html
  csunplugged/topics/content/de/binary-numbers/unit-plan/lessons/how-binary-digits-work-junior.md
  csunplugged/topics/content/de/binary-numbers/unit-plan/lessons/how-binary-digits-work.md
  csunplugged/topics/content/de/binary-numbers/unit-plan/unit-plan.md
  csunplugged/topics/content/de/sorting-networks/unit-plan/lessons/reinforcing-numeracy-through-a-sorting-network-junior.md
  csunplugged/topics/content/de/sorting-networks/unit-plan/unit-plan.md
  csunplugged/topics/content/en/binary-numbers/unit-plan/lessons/how-binary-digits-work-junior.md
  csunplugged/topics/content/en/binary-numbers/unit-plan/lessons/how-binary-digits-work.md
  csunplugged/topics/content/en/binary-numbers/unit-plan/unit-plan.md
  csunplugged/topics/content/en/error-detection-and-correction/unit-plan/lessons/parity-magic-junior.md
  csunplugged/topics/content/en/error-detection-and-correction/unit-plan/lessons/parity-magic.md
  csunplugged/topics/content/en/error-detection-and-correction/unit-plan/lessons/product-code-check-digits.md
  csunplugged/topics/content/en/error-detection-and-correction/unit-plan/unit-plan.md
  csunplugged/topics/content/en/sorting-networks/unit-plan/lessons/reinforcing-numeracy-through-a-sorting-network-junior.md
  csunplugged/topics/content/en/sorting-networks/unit-plan/lessons/reinforcing-numeracy-through-a-sorting-network.md
  csunplugged/topics/content/en/sorting-networks/unit-plan/unit-plan.md
  csunplugged/topics/content/es/binary-numbers/unit-plan/lessons/how-binary-digits-work.md
  csunplugged/topics/content/es/binary-numbers/unit-plan/unit-plan.md
  csunplugged/topics/content/fr/binary-numbers/unit-plan/unit-plan.md
  csunplugged/topics/content/mi/error-detection-and-correction/unit-plan/lessons/parity-magic-junior.md
  csunplugged/topics/content/mi/error-detection-and-correction/unit-plan/lessons/parity-magic.md
  csunplugged/topics/content/mi/error-detection-and-correction/unit-plan/unit-plan.md
  csunplugged/topics/content/mi/sorting-networks/unit-plan/unit-plan.md
  csunplugged/topics/content/xx_LR/binary-numbers/unit-plan/lessons/how-binary-digits-work-junior.md
  csunplugged/topics/content/xx_LR/binary-numbers/unit-plan/lessons/how-binary-digits-work.md
  csunplugged/topics/content/xx_LR/binary-numbers/unit-plan/unit-plan.md
  csunplugged/topics/content/xx_LR/error-detection-and-correction/unit-plan/lessons/parity-magic-junior.md
  csunplugged/topics/content/xx_LR/error-detection-and-correction/unit-plan/lessons/parity-magic.md
  csunplugged/topics/content/xx_LR/error-detection-and-correction/unit-plan/lessons/product-code-check-digits.md
  csunplugged/topics/content/xx_LR/error-detection-and-correction/unit-plan/unit-plan.md
  csunplugged/topics/content/xx_LR/sorting-networks/unit-plan/lessons/reinforcing-numeracy-through-a-sorting-network-junior.md
  csunplugged/topics/content/xx_LR/sorting-networks/unit-plan/lessons/reinforcing-numeracy-through-a-sorting-network.md
  csunplugged/topics/content/xx_LR/sorting-networks/unit-plan/unit-plan.md
  csunplugged/topics/content/zh_Hans/binary-numbers/unit-plan/lessons/how-binary-digits-work.md
  csunplugged/topics/content/zh_Hans/binary-numbers/unit-plan/unit-plan.md
  subtitles/en/parity-magic-trick.vtt
  subtitles/fr/parity-magic-trick.vtt
Labels: content: other, frontend

#1414 Add definition for returning to parent in Implementation model
  csunplugged/topics/models.py
Labels: bug

#1416 Fix spelling of references to CSU licence files in README
  README.md
Labels: documentation, project style

#1415 Use Djano's JavaScript translation catalog
  LICENCE-THIRD-PARTY
  csu
  csunplugged/config/settings/base.py
  csunplugged/static/js/editor-options-menu.js
  csunplugged/static/js/test-code.js
  csunplugged/static/js/website.js
  csunplugged/templates/core.html
  docs/source/developer/translation_infrastructure.rst
  requirements/base.txt
  third-party-licences/django-statici18n.txt
Labels: backend, internationalization

#1419 Fix link in binary tunes
  csunplugged/topics/content/de/binary-numbers/curriculum-integrations/binary-tunes.md
  csunplugged/topics/content/en/binary-numbers/curriculum-integrations/binary-tunes.md
  csunplugged/topics/content/es/binary-numbers/curriculum-integrations/binary-tunes.md
  csunplugged/topics/content/fr/binary-numbers/curriculum-integrations/binary-tunes.md
  csunplugged/topics/content/mi/binary-numbers/curriculum-integrations/binary-tunes.md
Labels: bug
